#!/usr/bin/env ruby

home = File.expand_path('~')

Dir['*'].each do |file|
  next if file =~ /bootstrap|README/
  target = File.join(home, ".#{file}")

  if File.symlink? target
    next
  elsif File.exist? target
    puts "Skipped #{file} (target already exists)"
    next
  end

  `ln -s #{File.expand_path file} #{target}`
  puts "Linked ~/.#{file} -> #{file}"
end


# Prepare NeoBundle

unless File.directory? "vim/bundle/neobundle.vim"
  puts "Cloning Shougo/neobundle.vim"
  `git clone git://github.com/Shougo/neobundle.vim vim/bundle/neobundle.vim`
end
