# Key bindings
keybind = ctrl+shift+c=copy_to_clipboard
keybind = ctrl+shift+v=paste_from_clipboard
keybind = shift+enter=text:\n

# Typography
font-family =
font-family = FiraCode Nerd Font
font-family = Apple Color Emoji
font-size = 12

# Window
window-padding-x = 12
window-padding-y = 12
window-theme = ghostty
window-padding-balance = true
window-decoration = server
background-opacity = 0.95
background-blur = true
