# $PATH

ORIGINAL_PATH=$PATH
PATH=""
# local directory
PATH="$PATH:./bin"
# personal bin directory
PATH="$PATH:$HOME/.bin"
# homebrew
PATH="$PATH:/usr/local/bin"
PATH="$PATH:/usr/local/sbin"
PATH="$PATH:/usr/local/share/python"
PATH="$PATH:/usr/local/share/npm/bin"

export PATH="$PATH:$ORIGINAL_PATH"
