add_newline = false
command_timeout = 500

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[cmd_duration]
disabled = true

[hostname]
style = "bold yellow"

[directory]
truncation_length = 8

[username]
format = "[$user@]($style)"
