add_newline = false
command_timeout = 500

format = """
$username\
$hostname\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$all\
$character"""

[fill]
symbol = " "
style = ""

[aws]
symbol = "  "

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[conda]
symbol = " "

[cmake]
format = "[$symbol($version )]($style)"

[cmd_duration]
disabled = true

[hostname]
ssh_symbol = ""
style = "bold yellow"

[dart]
symbol = " "
format = "[$symbol($version )]($style)"

[deno]
format = "[$symbol($version )]($style)"

[directory]
truncation_length = 8
read_only = " "

[docker_context]
symbol = " "
format = "[$symbol$context]($style) "

[elixir]
symbol = " "
format = '[$symbol($version \(OTP $otp_version\) )]($style)'

[elm]
symbol = " "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[git_commit]
tag_disabled = false
tag_symbol = "  "

[git_status]
style = "black"

[golang]
symbol = " "
format = "[$symbol($version )]($style)"

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"

[package]
symbol = " "

[perl]
symbol = " "
format = "[$symbol($version )]($style)"

[php]
symbol = " "
format = "[$symbol($version )]($style)"

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[ruby]
symbol = " "
format = "[$symbol($version )]($style)"

[rust]
symbol = " "
format = "[$symbol($version )]($style)"

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[username]
format = "[$user@]($style)"

