#!/bin/bash

if [ ! -d $HOME/.zplug ]; then
  mkdir -p $HOME/.zplug/repos/zplug
  git clone https://github.com/zplug/zplug $HOME/.zplug/repos/zplug/zplug
  ln -sf $HOME/.zplug/repos/zplug/zplug/init.zsh $HOME/.zplug/init.zsh
fi

if [ -d $HOME/.vim ] && [ ! -d $HOME/.vim/backup ]; then
  mkdir -p $HOME/.vim/backup
fi

if [ ! -f $HOME/.vim/autoload/plug.vim ]; then
  curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim -u $HOME/.vimrc.bundles +PlugInstall +qa
fi
