#!/bin/sh

if [ ! -d $HOME/.oh-my-zsh ]; then
  git clone https://github.com/robbyrussell/oh-my-zsh $HOME/.oh-my-zsh
fi

if [ -d $HOME/.vim ] && [ ! -d $HOME/.vim/backup ]; then
  mkdir -p $HOME/.vim/backup
fi

if [ ! -e $HOME/.config/base16-shell ]; then
  mkdir -p $HOME/.config
  git clone https://github.com/chriskempson/base16-shell.git $HOME/.config/base16-shell
fi

if [ ! -e $HOME/.vim/bundle/neobundle.vim ]; then
  git clone https://github.com/Shougo/neobundle.vim $HOME/.vim/bundle/neobundle.vim
  vim -u $HOME/.vimrc.bundles +NeoBundleInstall +qa
fi
