#!/bin/bash

if [ ! -d $HOME/.znap/zsh-snap ]; then
  echo "Installing zsh-snap"
  mkdir -p $HOME/.znap
  git clone https://github.com/marlonrichert/zsh-snap.git $HOME/.znap/zsh-snap
fi

if [ ! -d $HOME/.asdf ]; then
  echo "Installing asdf"
  asdf_release=$(curl --silent "https://api.github.com/repos/asdf-vm/asdf/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
  git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf --branch ${asdf_release:-master}
  source $HOME/.asdf/asdf.sh
  for plugin in direnv nodejs ruby; do asdf plugin-add $plugin; done
fi

if ! hash starship &>/dev/null && [ ! -f $HOME/.local/bin/starship ]; then
  echo "Installing starship"
  sh -c "$(curl -sS https://starship.rs/install.sh)" -- -y -b $HOME/.local/bin
fi

if [ -d $HOME/.vim ] && [ ! -d $HOME/.vim/backup ]; then
  mkdir -p $HOME/.vim/backup
fi

if [ ! -f $HOME/.vim/autoload/plug.vim ]; then
  curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim -u $HOME/.vimrc.bundles +PlugInstall +qa
fi

if hash bat &>/dev/null && [ ! -f "$(bat --config-dir)/themes/Oceanic Next.tmTheme" ]; then
  curl -fLo "$(bat --config-dir)/themes/Oceanic Next.tmTheme" --create-dirs https://raw.githubusercontent.com/voronianski/oceanic-next-color-scheme/master/Oceanic%20Next.tmTheme
  bat cache --build
fi
